### ISSUE TITLE
Immersive Engineering Concrete becomes uncraftable with this mod installed

### ISSUE THREAD

**Issue by Cynix32** [EnderiumSmith/CharcoalPit2#1]
MC 1.16.5
Java 8
Forge 36.1.3
CharcoalPit[1.16.5]-2.9.jar

Mods that use clay and other clay related items in their recipes are incompatible with this mod. The mods in question are Immersive Engineering (latest version) and Immersive Petroleum (also latest version)

To be specific, Concrete and some other recipes that use clay becomes uncraftable when Charcoal Pit is installed along with those mods. Only some recipes are affected like concrete and asphalt concrete. Take note that I did not modify any recipe via a datapack & CraftTweaker is also not installed. The recipe for concrete/asphalt that uses clay balls get removed for some reason, even in the mixer machine, which makes IE concrete literally unobtainable.

Mods installed to reproduce the problem
The problem being that Immersive Engineering/Petroleum Concrete becomes uncraftable when Charcoal Pit is also installed.

CharcoalPit[1.16.5]-2.9.jar
ImmersivePetroleum-1.16.5-3.2.0-3.jar
ImmersiveEngineering-1.16.5-4.2.3-133.jar
JEI

The problem also exists when only Immersive Engineering and Charcoal Pit is installed.

Additional information:
When loading a world, console spits this out:
pastebin.com/wQm9gz4J

**Comment by EnderiumSmith** [comment]
i have no idea why. it works for things like hempcrete. it seems this has something to do with the fluid crafting recipes. post this on IE. They might be able to figure it out better.

**Comment by Cynix32** [comment]
Apparently it is indeed an issue on their side, see BluSunrize/ImmersiveEngineering#4770. Closing this issue now since they have seemed to pinpoint the issue.
