### ISSUE TITLE
Coal is not accepted as fuel.

### ISSUE THREAD

**Issue by Cynix32** [EnderiumSmith/CharcoalPit2#3]
Java 8
MC 1.16.5
Forge 36.1.13
CharcoalPit[1.16.5]-2.11.2.jar

The clay vessel somehow does not accept coal as fuel.

![Screenshot (141)](https://user-images.githubusercontent.com/69455883/116030727-d0962600-a68e-11eb-970c-57ece45cdfe4.png)
![Screenshot (142)](https://user-images.githubusercontent.com/69455883/116030792-f4f20280-a68e-11eb-81e4-573626d62889.png)

**Comment by EnderiumSmith** [comment]
yes i found out about this. i fixed it in dev  a while ago but was trying to figure out why the server was crashing
