### ISSUE TITLE
[FEATURE REQUEST] Add Compatibility for Bricks/Blocks from Other Mods to be Used as Refractory Blocks

### ISSUE THREAD

**Issue by Cynix32** [EnderiumSmith/CharcoalPit2#4]
This is a request to at least add a config option or another way to add blocks/bricks from other mods to be compatible and act as refractory blocks with this mod's kiln/oven/bloomery/etc...

I had this idea when I tried playing charcoal pit and several other mods (ie quark that adds cobblestone and mud bricks) in my own personal modpack  that add different bricks and dyed brick blocks. Those blocks do not work as refractory blocks for the purposes of this mod as this mod only recognizes bricks from vanilla MC (clay brick, nether brick, ender brick) and the sandy brick from this mod. Because of this, I am stuck to the vanilla bricks to use as refractory blocks, which is tad bummer.

lmao i noticed that I am the one submitting most issues here in your github so sorry for that I guess.

**Comment by EnderiumSmith** [comment]
you already can add them. its just a block tag that you can add to with a resource pack or just editing the assets in the jar. 

I dont think i can add default entries as it will crash if the entry doesnt exist.

**Comment by Cynix32** [comment]
Looking from the code, I assume the block tag charcoalpit:refractory_bricks will automatically be have the block tags for coke oven walls and bloomery walls right?

So basically I have to add the refractory_bricks block tag for the block I want by creating a resource pack?

**Comment by EnderiumSmith** [comment]
yes. the bricks tag applies to both coke ovens and bloomeries. you can also add to the walls tag if you only want it to apply to 1 like iron doors are valid for coke ovens but not bloomeries.

**Comment by Cynix32** [comment]
Alright got it. Thanks!
