### ISSUE TITLE
[1.16] Bloomery recipe input is bugged

### ISSUE THREAD

**Issue by rowanthemodder** [EnderiumSmith/CharcoalPit2#5]
Charcoal Pit Version: 2.13
Forge Version: 36.1.16

All recipes for the bloomery, including custom ones made via datapack, default to nickel ore as the input. This is also reflected in JEI.

To Reproduce: Load up the game with charcoal pit and JEI installed and check JEI, and/or try to put iron ore in a bloomery with shift right click like nickel ore.

**Comment by EnderiumSmith** [comment]
can you be more clear? if you load just charcoal pit and jei there would be no nickel. do you mean all recipes show nickel as input and you can only put nickel in it? what happens when it completes?

**Comment by rowanthemodder** [comment]
My apologies, this was a case of user error when writing recipes.
